import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import RecoilProvider from "@/providers/Recoil";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<RecoilProvider>
				<Header />
				<body className={`${inter.className}`}>{children}</body>
			</RecoilProvider>
		</html>
	);
}
